### ISSUE TITLE
v-else without  value breaks highlighting

### ISSUE THREAD

**Issue by amerov** [leafOfTree/vim-vue-plugin#11]
![Screenshot from 2019-06-20 00-43-06](https://user-images.githubusercontent.com/196747/59795318-670b9a80-92f4-11e9-9969-0cd586f914ac.png)

**Comment by leafOfTree** [comment]
Thank you for feedback. `v-else` directive was missed before.

**Comment by leafOfTree** [comment]
Syntax match regexp is improved. The highlighting should be ok now.

**Comment by amerov** [comment]
> Syntax match regexp is improved. The highlighting should be ok now.
:+1:
