### ISSUE TITLE
Number with munis sign not highlighted

### ISSUE THREAD

**Issue by amerov** [leafOfTree/vim-vue-plugin#12]
![Screenshot from 2019-06-26 16-16-30](https://user-images.githubusercontent.com/196747/60175748-e0901500-982d-11e9-9403-cfec5eaff584.png)
`-10` recognized as a `vueScript`

**Comment by leafOfTree** [comment]
Hi, as `vueScript` is a basic syntax for all wrapped in `<script>`,  it should be related to the syntax of javascript.
Could you test number syntax in a normal `javascript` file? And what javascript syntax plugin do you use?
Here is my syntax highlighting:

default javascript syntax:
![LTvKKH7CZD](https://user-images.githubusercontent.com/13349592/60228695-15e84180-98c6-11e9-9c1e-96ac1e1a2ccb.png)

with 'pangloss/vim-javascript' enabled:
![8vNEgR9dIi](https://user-images.githubusercontent.com/13349592/60228831-8f802f80-98c6-11e9-9de5-ea3feef59569.png)

**Comment by amerov** [comment]
> Hi, as `vueScript` is a basic syntax for all wrapped in `<script>`, it should be related to the syntax of javascript.
> Could you test number syntax in a normal `javascript` file? And what javascript syntax plugin do you use?
> Here is my syntax highlighting:
> 
> default javascript syntax:
> ![LTvKKH7CZD](https://user-images.githubusercontent.com/13349592/60228695-15e84180-98c6-11e9-9c1e-96ac1e1a2ccb.png)
> 
> with 'pangloss/vim-javascript' enabled:
> ![8vNEgR9dIi](https://user-images.githubusercontent.com/13349592/60228831-8f802f80-98c6-11e9-9de5-ea3feef59569.png)

Normal js syntax is okay.
I use 'pangloss/vim-javascript'
My vimrc: https://github.com/amerov/dotfiles/blob/master/.config/nvim/init.vim

**Comment by leafOfTree** [comment]
Thank you for sharing your vimrc. I need more info to debug. There is a `SynStack` function in it. Could you move the cursor to `-10` 's `-` and `10` and 

    :call SynStack()

It will display all syntax applied to them. For the latest `vim-javascript`(It has been updated recently), there should be `jsOperator` for `-` and `jsNumber` for `10`.

And try

    :verb hi jsOperator
    :verb hi jsNumber

to show detail info.

**Comment by amerov** [comment]
synStack result for `10`: ['vueScript', 'jsObject', 'jsFuncBlock'] 
synStack result for `-`: ['vueScript', 'jsObject', 'jsFuncBlock', 'jsOperator']

```viml
:verb hi jsNumber                                                                                                                                                                           
jsNumber       xxx links to Number
        Last set from ~/.local/share/nvim/plugged/vim-javascript/syntax/javascript.vim
```
```viml
:verb hi jsOperator                                                                                                                                                                         
jsOperator     xxx links to Operator
        Last set from ~/.local/share/nvim/plugged/vim-javascript/syntax/javascript.vim
```

**Comment by amerov** [comment]
when `let g:vim_vue_plugin_load_full_syntax=0` number with minus highlighting is ok. But html's data attributes  isn't.

**Comment by leafOfTree** [comment]
Thank you for the feedback. I use gVim and will try Neovim to see what happens.

**Comment by leafOfTree** [comment]
Yes. `let g:vim_vue_plugin_load_full_syntax=1`  and using `othree/html5.vim`  reproduce this error.

**Comment by leafOfTree** [comment]
`othree/html5.vim` uses `syn iskeyword` (see `:h syn-iskeyword`) that adds `-` to iskeyword option, causing `-10` highlighting error. I have replaced `-` with `$` for `vue`.

**Comment by amerov** [comment]
![Screenshot from 2019-07-02 14-33-43](https://user-images.githubusercontent.com/196747/60502034-71576c80-9cd6-11e9-89c2-adbc0dc5ae71.png)
Now html's data attributes broken.

**Comment by leafOfTree** [comment]
I didn't consider the impact on HTML attributes(for which `-` is required in syntax keyword). Then I adjusted the javascript number highlighting pattern so both are satisfied now.

**Comment by amerov** [comment]
Thanks!
Now current state is ok.
Also I open issue for html5 plugin https://github.com/othree/html5.vim/issues/103
