### ISSUE TITLE
Support coffeescript inside <script lang="coffee">

### ISSUE THREAD

**Issue by mat813** [leafOfTree/vim-vue-plugin#14]
The coffeescript plugin support is available here : https://github.com/kchmck/vim-coffee-script

**Comment by leafOfTree** [comment]
Thank you for the suggestion. It should support `CoffeeScript` now when adding

    let g:vim_vue_plugin_use_coffee = 1

**Comment by mat813** [comment]
Works great, thank you so much :-)
