### ISSUE TITLE
Install plugin via pathogen

### ISSUE THREAD

**Issue by rolzing** [leafOfTree/vim-vue-plugin#2]

**Comment by leafOfTree** [comment]
Hi, thanks for the suggestion. Let me know if it works.

**Comment by rolzing** [comment]
Getting this err

> ❯ vim
> Error detected while processing .../my_plugins/vim-vue-plugin/filetype.vim:
> line    2:
> E492: Not an editor command: ^M
> line    3:
> E488: Trailing characters
> line   10:
> E492: Not an editor command: ^M
> line   11:
> E15: Invalid expression: !exists("g:vim_vue_plugin_has_init_indent")^M
> line   17:
> E171: Missing :endif
> Press ENTER or type command to continue

**Comment by leafOfTree** [comment]
There were some Unix related issues fixed.

**Comment by leafOfTree** [comment]
It seems to work with pathogen, so I'm closing this issue. Feel free to reopn it if any error occurs.
