### ISSUE TITLE
Please, support single ticks for language definition

### ISSUE THREAD

**Issue by zezic** [leafOfTree/vim-vue-plugin#21]
Like not only the `<template lang="pug">` but also the `<template lang='pug'>`.

**Comment by leafOfTree** [comment]
Hi, thanks for the feedback. Single quote support has been added. `lang='pug'` should work now.
https://github.com/leafOfTree/vim-vue-plugin/commit/d6a25fc824e3fafa6fbf556566a562d68ca54771

**Comment by zezic** [comment]
Thank you for fast response! I can confirm that it works now.
