### ISSUE TITLE
Sass using vim-emmet issue

### ISSUE THREAD

**Issue by mickeylin** [leafOfTree/vim-vue-plugin#23]
When I used vim-emmet in tag <style lang="sass">

I expect when I type t20px it should be 
```
card
   top: 20px
```

but it is
```
card
  t20px {
  
  }
```

Sass syntax is correct. It seems that vim-emmet dosen't determine the filetype is sass 
Even it is declared in the style tag
If it works, it will be perfect to me!

**Comment by leafOfTree** [comment]
Hi, thanks for reporting the sass issue. It requires both plugins to be updated.

 I've updated sass syntax name in this plugin. Also, I created a PR https://github.com/mattn/emmet-vim/pull/485. But it's not sure if it will get merged. So if you like, you can modify your local emmet-vim:
`emmet-vim/autoload/emmet.vim`, about line 393
```diff
  if type =~? '^css'
    let type = 'css'
+ elseif type =~? '^sass'
+   let type = 'sass'
  elseif type =~? '^html'
    let type = 'html'
```

**Comment by mickeylin** [comment]
Thanks for fast response and updating. It works!
What a  awesome plugin!
