### ISSUE TITLE
No highlighting with "wrong" indentation

### ISSUE THREAD

**Issue by suruaku** [leafOfTree/vim-vue-plugin#25]
As you can see in the screenshots highlighting wasn't working when I had my indentation a bit of.
I have `g:vim_vue_plugin_highlight_vue_keyword=1` in my vimrc.

Berofe:
![image](https://user-images.githubusercontent.com/43464534/95513611-4a044a80-09c3-11eb-8ba2-75b33bd7b724.png)

After:
![image](https://user-images.githubusercontent.com/43464534/95513666-5c7e8400-09c3-11eb-92bd-b1411ac892c0.png)

**Comment by leafOfTree** [comment]
Thanks for the feedback. I checked the code and realised that the highlighting only effects for the keyword with correct indentation. 
It is to prevent highlighting when the inner object uses the keyword as key.
```javascript
export default {
  data: {
    data: {
    }
  },
  computed: {
    name: {
    }
  }
}
```
I wonder if you don't have the nested cases and have to deal with some "wrong" indentation codes, maybe we can add an option to toggle it.

**Comment by suruaku** [comment]
Okay, I get it. Could it be so that only first data object is highlighted? Since it's always the first one.

Now while testing, I also noticed that if you use async with for example mounted() it doesn't get highlighted either.

With async:
![image](https://user-images.githubusercontent.com/43464534/95579258-f71ba900-0a3d-11eb-9316-8ade913eb715.png)

Without async:
![image](https://user-images.githubusercontent.com/43464534/95579331-17e3fe80-0a3e-11eb-8e1e-b29cc6ed2b7a.png)

**Comment by leafOfTree** [comment]
Hi, I have to say it seems not easy to highlight only the first data object.

The async has been resolved with b8e23259e2453b3d56171c1d59e855e18c415acd and 559d93c6ba6a857696f7849baca0d2b9b0dfd0f8 . Please update and see if it works.

**Comment by suruaku** [comment]
Okay, it's not a huge issue so maybe it's better to leave it as it is. (I have no experience with vim extensions and those regex patterns look a bit scary :D) 

Async works now, thanks!

**Comment by leafOfTree** [comment]
You're welcome. I'll close this issue. Feel free to open another issue if you may have any problem with it.
