### ISSUE TITLE
Add option to set indent width

### ISSUE THREAD

**Issue by starmatt** [leafOfTree/vim-vue-plugin#27]
Hello,

It seems that this plugin (best one I've tried for vue btw :heart: ) is overriding my global setting of using 4 spaces for indenting.
By default when the plugin is active, new lines are indented with 2 spaces.
Can you add an option to let us choose the indent width, or use the option set in the vimrc by default ?

Thanks for your attention!

**Comment by leafOfTree** [comment]
Hi, thank you for trying it and giving the feedback. :smile:

The plugin should only set local indent width, but I agree with you that it's better to leave it as a user option. https://github.com/leafOfTree/vim-vue-plugin/commit/2802a661bd261fbd9299c7223fb04b93b0d69776 Please update and help verify if it works.

**Comment by starmatt** [comment]
Works great now, thanks a lot !
