### ISSUE TITLE
Add support for <transition> attributes

### ISSUE THREAD

**Issue by starmatt** [leafOfTree/vim-vue-plugin#28]
Hello again,

I've noticed `<transition>` attributes ([see docs for full list](https://v3.vuejs.org/guide/transitions-enterleave.html#custom-transition-classes)) don't get highlighted like other vue attributes. Here's a screenshot showing what I mean:
![transition syntax](https://i.imgur.com/NVOm5qa.png)

These attributes are linked to the `htmlTag` group instead of `VueKey` or `htmlArg`.

I also want to make a small side-note, unrelated to your plugin: do you know if there is a way to link all custom HTML attributes to the `htmlArg` group ? I know vim just doesn't highlight attributes it doesn't recognize, but it's been driving me crazy and I've been looking for a way to overcome this limitation.

Thanks again for your help and attention, and again, awesome plugin !

**Comment by leafOfTree** [comment]
Hi, thanks for the feedback and suggestion. I've updated the plugin to support the transition attributes as `htmlArg`. 
Also, if you want to highlight all custom HTML attributes as `htmlArg`, you can try and add
```vim
syntax match htmlArg contained "\<[-0-9A-Za-z_]\+\>"
```
to your custom syntax files like `vimfiles/syntax/html.vim` or `vimfiles/syntax/vue.vim`.

**Comment by starmatt** [comment]
Working great, thanks a lot !

**Comment by leafOfTree** [comment]
Glad to hear that. I just found that there was something wrong with the custom `htmlArg` pattern. Please try this corrected one
```vim
syntax match htmlArg contained "\<[-0-9A-Za-z_]\+\>"
```
