### ISSUE TITLE
Vue SFC custom block support ?

### ISSUE THREAD

**Issue by IndexXuan** [leafOfTree/vim-vue-plugin#29]
Thanks for this awesome plugin.
can we support Vue SFC custom block like <i18n lang="yml">, <route lang="json"> or something.

e.g. https://github.com/intlify/vite-plugin-vue-i18n
e.g. https://github.com/ktsn/vue-route-generator#route-custom-block

thanks a lot.

**Comment by leafOfTree** [comment]
That's a good idea. Definitely, we should. I'll check it soon.

**Comment by leafOfTree** [comment]
I've added the feature. Please try and let me know if it works. 

Here's the doc: https://github.com/leafOfTree/vim-vue-plugin#custom-blocks

Example
```vim
let g:vim_vue_plugin_custom_blocks = { 
      \'docs': 'markdown',
      \'i18n': ['json', 'yaml', 'json5'],
      \}
```

Should highlight custom blocks in `.vue` file such as

```vue
<docs>
# This is the documentation for component.
</docs>

<i18n lang="yaml">
en:
  hello: "Hello World!"
ja:
  hello: "こんにちは、世界！"
</i18n>
```

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/110764566-2dc84a80-828e-11eb-841e-d28df172c3ea.png)
sorry, there are some errors .

**Comment by leafOfTree** [comment]
Hi, IndexXuan, which vim version do you use? It seems that your vim doesn't support the `optional function argument`. I've replaced it with a normal argument. Hope it'll solve the errors. https://github.com/leafOfTree/vim-vue-plugin/commit/b24ce563611a7041c8a2e7ded82e7f30fbe88e17

**Comment by leafOfTree** [comment]
Also, you probably need to install a vim json5 plugin since vim doesn't support it by default yet.

**Comment by IndexXuan** [comment]
@leafOfTree It works, thanks for this awesome plugin. switch from vim-vue to it now.
also I am use nvim 0.5.0.

yes, after install json5 plugin, it even work for json-like syntax.
