### ISSUE TITLE
no syntax highlighting after </template>

### ISSUE THREAD

**Issue by maciejg-git** [leafOfTree/vim-vue-plugin#30]
![vim-vue](https://user-images.githubusercontent.com/41588433/112829737-d4378c80-9091-11eb-9262-1a92f307e7b7.png)
:echo GetVueTag() return empty after `</template>` inside template.

**Comment by leafOfTree** [comment]
Hi, thank you for the timely report. It's caused by the upgrade. I've adjusted the syntax pattern to fix it. Please update and see if it works.

**Comment by maciejg-git** [comment]
![vue](https://user-images.githubusercontent.com/41588433/112980659-6e630780-915a-11eb-82d3-e653660b091a.png)
Thanks for the fix. I updated and still have some issues with nested templates. I'm using Neovim 5.0-dev.
Edit: I made some tests and it works without new lines. 
![test](https://user-images.githubusercontent.com/41588433/112982971-65276a00-915d-11eb-92c4-ad33a7aa6518.png)

**Comment by alferguet** [comment]
Having the same issue as well having just installed the plugin.

**Comment by leafOfTree** [comment]
Hey, folks. 
I only checked the situation without newlines last time. Now I've used a more strict syntax pattern to avoid this problem. Please check it out.

<img width="177" alt="Screen Shot 2021-03-31 at 6 55 30 PM" src="https://user-images.githubusercontent.com/13349592/113133816-acdbed80-9252-11eb-8d52-2f05c46d189c.png">

**Comment by alferguet** [comment]
It works perfectly now, thanks for the update! 
Still need to experiment a little bit with the syntax options to tweak it but loving it so far 💯

**Comment by maciejg-git** [comment]
It works now, thanks.

**Comment by leafOfTree** [comment]
Great.

**Comment by maciejgralek** [comment]
Fixed.
