### ISSUE TITLE
no highlight after loading session

### ISSUE THREAD

**Issue by maciejg-git** [leafOfTree/vim-vue-plugin#31]
![test](https://user-images.githubusercontent.com/41588433/113180444-07744a00-9251-11eb-962d-afc310b25626.png)
After loading session with two or more windows only one window have highlight. Steps to reproduce:
-split window and load 2 different vue files
-save session
-restart vim and load session

**Comment by leafOfTree** [comment]
I use `timer_start` to speed up this plugin. However, it doesn't work well with session which switches buffers too quickly. So I disabled it when loading session to fix it. Please check it out.
<img width="661" alt="Screen Shot 2021-04-01 at 10 41 20 AM" src="https://user-images.githubusercontent.com/13349592/113236161-f3732b80-92d6-11eb-8922-4e3558147cbf.png">

**Comment by maciejg-git** [comment]
It works, thanks.
