### ISSUE TITLE
Custom syntax block indentation

### ISSUE THREAD

**Issue by suruaku** [leafOfTree/vim-vue-plugin#32]
The new ability to add syntax blocks is awesome, thanks for that!

Do you know is it possible to make indentation work correctly when formatting with [`gg=G`](https://vim.fandom.com/wiki/Fix_indentation)? 

It works perfectly with template, script and style parts. But the i18n yaml block (has correct highlighting) but is indented completely wrong with command `gg=G`.

```
let g:vim_vue_plugin_config = {
      \'syntax': {
      \   'template': ['html'],
      \   'script': ['javascript'],
      \   'style': ['css'],
      \   'i18n': ['yaml'],
      \},
      \'full_syntax': [],
      \'attribute': 1,
      \'keyword': 1,
      \'foldexpr': 0,
      \'init_indent': 0,
      \'debug': 0,
      \}
```

**Comment by leafOfTree** [comment]
Hi, the custom block indentation is supposed to work for `yaml`. I'm not sure, but I've seen similar issues for Vim of certain versions. Could you tell me your Vim version?

**Comment by suruaku** [comment]
Oh, okay, silly me, should have tested this with fresh vim. That's something wrong with my setup since indenting works in fresh vim with just your plugin! Sorry for inconvenience.

**Comment by leafOfTree** [comment]
No problem
