### ISSUE TITLE
I wanted something that folds vue files properly. The folds are improper.

### ISSUE THREAD

**Issue by aasutossh** [leafOfTree/vim-vue-plugin#34]
I am using the config https://github.com/leafOfTree/vim-vue-plugin#example.

Currently the `<template>` don't get folded.
It folds the `script` and `style` tag but it's weird.
![image](https://user-images.githubusercontent.com/18498932/120913013-a08d6a00-c6b3-11eb-9f9d-6d92b88c9a3f.png)
![image](https://user-images.githubusercontent.com/18498932/120913020-b6029400-c6b3-11eb-9d8d-fdc65081c0d8.png)

**Comment by leafOfTree** [comment]
Hi, thanks for your feedback. I'm sorry that I couldn't respond earlier.

I tried a file with the example config and then toggled folding with `zM` and `zR`. It looks like below, which looks proper to me.
Can you try it and see if it works for you, too? Or can you share a minimal example file that folds improperly?

```vue
<template>
  <p>{{ greeting }}</p>
</template>

<script>
export default {
  data: function () {
    return {
      greeting: 'Hello'
    };
  },
};
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
  background: rgb(0, 0, 0, 0.7);
}
</style>
```

<img width="363" alt="Screen Shot 2021-06-15 at 11 05 52 AM" src="https://user-images.githubusercontent.com/13349592/121986812-c8728100-cdc9-11eb-882e-ffbc3185a808.png">

**Comment by leafOfTree** [comment]
Please note that you can verify it with a minimal confg like
```vim
  let g:vim_vue_plugin_config = { 
        \'syntax': {
        \   'template': ['html'],
        \   'script': ['javascript'],
        \   'style': ['css'],
        \},
        \'foldexpr': 1,
        \}

```

**Comment by leafOfTree** [comment]
I'm closing this issue. Feel free to reopen It if you still have an issue with the latest version.

**Comment by aasutossh** [comment]
hi, could you look at this?
https://youtu.be/o7VmFe0UbFA

I tried folding and unfolding at multiple places, it doesn't fold just one tag, but rather folds the whole template section.
I was supposed to be able to fold and unfold a single tag, wasn't I?

**Comment by aasutossh** [comment]
>  I was supposed to be able to fold and unfold a single tag, wasn't I?

Nevermind, it's working as expected now.
