### ISSUE TITLE
Neovim setup?

### ISSUE THREAD

**Issue by im-n1** [leafOfTree/vim-vue-plugin#38]
Hi I'm trying to set this plugin up on Neovim and it doesn't highlight work at all. When I turn on debug ths is what I get

```
"~/workspace/richy/app/app/richy/core/static/js/components/item_chart.vue" 478L, 13488B
[vim-vue-plugin] pug: syntax not found in ['$VIMRUNTIME', '$VIM/vimfiles', '$HOME/.vim']
[vim-vue-plugin] pug: load full instead
[vim-vue-plugin] pug: load full
"~/workspace/richy/app/app/richy/core/static/js/components/the_eye.vue" 100L, 2056B
[vim-vue-plugin] pug: syntax not found in ['$VIMRUNTIME', '$VIM/vimfiles', '$HOME/.vim']
[vim-vue-plugin] pug: load full instead
[vim-vue-plugin] pug: load full
"~/workspace/richy/app/app/richy/core/static/js/components/chart.vue" 122L, 2681B
[vim-vue-plugin] pug: syntax not found in ['$VIMRUNTIME', '$VIM/vimfiles', '$HOME/.vim']
[vim-vue-plugin] pug: load full instead
[vim-vue-plugin] pug: load full
[vim-vue-plugin] html: load default
```

What exacty I'm missing?

Thanks in advance.

**Comment by leafOfTree** [comment]
Hi, there. Sorry for the late response.

Could you confirm if it works with the default config and a simple .vue file? Is there no highlight at all, or is it broken?

Neovim seems to work for me with the default config
```vim
  let g:vim_vue_plugin_config = { 
      \'syntax': {
      \   'template': ['html'],
      \   'script': ['javascript'],
      \   'style': ['css'],
      \},
      \'full_syntax': [],
      \'initial_indent': [],
      \'attribute': 0,
      \'keyword': 0,
      \'foldexpr': 0,
      \'debug': 0,
      \}
```

![Screenshot 2023-01-31 at 13 23 37](https://user-images.githubusercontent.com/13349592/215672832-1b4305ef-aa21-4a0d-affd-04d9d98854d0.png)

**Comment by im-n1** [comment]
Sorry for the late response :)
Tried but sadly `<script>` is not highlighted at all.

**Comment by leafOfTree** [comment]
Hi, I tried again with nvim `v0.9.2` by simply adding this plugin to `runtimepath`. It looks good to me.
My guess is that there may be another plugin interfering with the syntax. Could you try excluding others and then see how it works?


init.vim
```
set runtimepath+=~/.vim/plugged/vim-vue-plugin
```
<img width="543" alt="Screen Shot 2023-09-22 at 17 09 59" src="https://github.com/leafOfTree/vim-vue-plugin/assets/13349592/684f72da-7f1b-4571-a526-838d40354367">

**Comment by im-n1** [comment]
After a long battle with node/npm/ts and slightly lsp I might have a clue - Looks like tree sitter is the problem. Once I disable it a vue file looks like this:

![image](https://github.com/leafOfTree/vim-vue-plugin/assets/198654/5fa2fb18-27ba-49d4-82d4-2155e3f166c6)

The script part is highlighted very poorly but it's still something.

**Comment by leafOfTree** [comment]
I see.

The script part uses the same basic syntax as a normal javascript file. You can try the `full_syntax` to include highlights from plugins.

```vim
  let g:vim_vue_plugin_config = { 
      \'syntax': {
      \   'template': ['html'],
      \   'script': ['javascript', 'typescript'],
      \   'style': ['css'],
      \},
      \'full_syntax': ['javascript', 'typescript'],
      \}
```

You can also try `nvim-treesitter` with `:TSInstall vue`, but not enable both plugins at the same time.

**Comment by im-n1** [comment]
Just tried treesitter's `vue` and it's amazing. We are done here, thanks.
