### ISSUE TITLE
Install plugin via Plug & typo in global variable settings

### ISSUE THREAD

**Issue by ashishwadekar** [leafOfTree/vim-vue-plugin#4]
Namaste,

Add installation information to use Vim Plug & there is a typo in the global variable settings
It is:
`let g:vim_uue_plugin_load_full_syntax = 1`

Should be:
`let g:vim_vue_plugin_load_full_syntax = 1`

I am willing to send a pull request for the same.

Cheers,
Ashish

**Comment by leafOfTree** [comment]
Of course. Pull request is welcome.
