### ISSUE TITLE
LICENSE missing?

### ISSUE THREAD

**Issue by creativecomposer** [leafOfTree/vim-vue-plugin#6]
Hi,
Thank you for the plugin.
Without a license, I could not decide whether I should use this plugin or not.

Could you please clarify under which license do you want to use?

Thanks.

**Comment by leafOfTree** [comment]
Hi,
Thanks for your feedback. [The Unlicense](https://choosealicense.com/licenses/unlicense/) is added.

Enjoy Vim and Vue.

**Comment by creativecomposer** [comment]
Thank you for the unlicense!
