### ISSUE TITLE
"%" key does not work on html/vue tags.

### ISSUE THREAD

**Issue by roket1428** [leafOfTree/vim-vue-plugin#8]
% key has to jump between tags by default in html/vue tags.
(cursor is [<any_char>]. So, [m] means cursor on the "m" char.)

Expected when pressing %:
```
<te[m]plate>                           <template>
  <vue-tag>                               <vue-tag>
    Dummy data        ===>                  Dummy data
  </vue-tag>                              </vue-tag>
</template>                             <[/]template>
```
But it doesn't do anything.
If you don't know what % does (I'm pretty sure you do) check it out with :h % in vim

You could check expected behavior with a normal html file.

**Comment by leafOfTree** [comment]
Thank you for reminding me of the useful `%` command. Its config is added and can be used for tags now.

**Comment by roket1428** [comment]
Thanks a lot man...
