### ISSUE TITLE
There are unexpected indentation problems.

### ISSUE THREAD

**Issue by roket1428** [leafOfTree/vim-vue-plugin#9]
As you can see on this image, there are unexpected indentation problems.
I use gg=G to auto-indent file.
![](http://magaimg.net/img/87zm.png)

**Comment by leafOfTree** [comment]
Thank you for this bug report.
XML indentation method is used for common tag indentation, which doesn't handle empty tags like `<input >` correctly( but `<input />`  I am used to writing ). 

So `<input />`, `<img />` ... self closed tags can get correct indentation for the time being. And I'll see if XML can handle empty tags later.

**Comment by leafOfTree** [comment]
My solution is only using HTML indentation for empty tags. Now it's ok to use both `<input>` and `<input />`.

**Comment by roket1428** [comment]
I'll not close this issue until I have enough experience with your plugin. But for now, it is working like a charm, good job man.

**Comment by roket1428** [comment]
There are still indentation problems. :)
![](http://magaimg.net/img/88ss.png)

**Comment by leafOfTree** [comment]
Yes, there are some indentation problems with `/>` followed by a blank line. Now it should work.

I haven't used IRC before. But I heard about freenode and have used Gitter. Maybe we can discuss issues in this Gitter room if you encounter them later.

https://gitter.im/vim-vue-plugin/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by roket1428** [comment]
Haha, I found another indentation error. :P 
If you add html comments that include tags in somewhere, indentation gets broken.
![](http://magaimg.net/img/8auc.png)

**Comment by leafOfTree** [comment]
Yes, indentation error occurs with `<input>` inside comments. It seems that mixed use of XML and HTML indentation causes some trouble. So now I only use XML indentation and patch it to indent as expected.

**Comment by roket1428** [comment]
Could you check your gitter out? I wanna show something.

**Comment by leafOfTree** [comment]
Sure.
